[#180] Fix in the test_metta_api.py integration test
